# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OverCode
email: daisymolving@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  OverCode is a simple blog about the programming languages that I am learning, and any ideas that I assemble from studying them. I hope it can serve as some use to someone who is also learning, or at least be somewhat morale-boosting. I am always keen to learn more, so if you spot something that isn't right, or something I can build on, please leave a comment or contact me. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daisymolving.github.io/" # the base hostname & protocol for your site
twitter_username: DaisyMolving
github_username:  DaisyMolving

comments: true

# Build settings
markdown: kramdown
